// repo_scaffold/templates/workspace_members/pnpm/vue-app/{{cookiecutter.member_name}}/src/App.vue
<script setup lang="ts">
const title = "Vue workspace app";
</script>

<template>
  <main class="min-h-screen bg-slate-950 p-8 text-slate-100">
    <section class="mx-auto max-w-3xl space-y-4">
      <p class="text-sm font-medium text-emerald-300">{{ cookiecutter.package_name }}</p>
      <h1 class="text-4xl font-bold tracking-tight">{% raw %}{{ title }}{% endraw %}</h1>
      <p class="text-slate-300">Vite, Tailwind CSS, Biome, and Vitest are ready.</p>
    </section>
  </main>
</template>

// repo_scaffold/templates/workspace_members/pnpm/react-app/{{cookiecutter.member_name}}/src/App.tsx
export function App() {
  return (
    <main className="min-h-screen bg-slate-950 p-8 text-slate-100">
      <section className="mx-auto max-w-3xl space-y-4">
        <p className="text-sm font-medium text-cyan-300">{{ cookiecutter.package_name }}</p>
        <h1 className="text-4xl font-bold tracking-tight">React workspace app</h1>
        <p className="text-slate-300">Vite, Tailwind CSS, Biome, and Vitest are ready.</p>
      </section>
    </main>
  );
}
